controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    wheel_controller:
      type: velocity_controllers/JointGroupVelocityController

wheel_controller:
  ros__parameters:
    joints:
      - flw_joint
      - frw_joint
      - rlw_joint
      - rrw_joint

    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity
